version: "3.7"

services:
  php:
    environment:
## Read instructions at https://wodby.com/stacks/drupal/docs/local/xdebug/
#      PHP_XDEBUG: 1
      PHP_XDEBUG_MODE: debug
      PHP_IDE_CONFIG: $PHP_IDE_CONFIG
      PHP_XDEBUG_IDEKEY: $PHP_XDEBUG_IDEKEY
      PHP_XDEBUG_CLIENT_HOST: host.docker.internal
      PHP_XDEBUG_LOG: /tmp/php-xdebug.log
#      # PHPUnit Drupal testing configurations
#      SIMPLETEST_BASE_URL: "http://${WEB_SERVER}"
#      SIMPLETEST_DB: "${DB_DRIVER}://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}#tests_"
#      MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", {"browserName":"chrome","goog:chromeOptions":{"args":["--disable-gpu","--headless"]}}, "http://chrome:9515"]'
    volumes:
    - drupal:/var/www/html

  crond:
    volumes:
    - drupal:/var/www/html

#  nginx:
#    volumes:
#    - drupal:/var/www/html

#  apache:
#    volumes:
#    - drupal:/var/www/html

#  node:
#    volumes:
#    - drupal:/var/www/html

volumes:
  drupal:

x-mutagen:
  sync:
    defaults:
      ignore:
        vcs: true
        paths:
        - .DS_Store
        - .history
        - .idea
        - .vscode
        - .git
    drupal:
      alpha: "."
      beta: "volume://drupal"
      configurationBeta:
        permissions:
          defaultFileMode: 0644
          defaultDirectoryMode: 0755
          defaultOwner: "id:501"
          defaultGroup: "id:20"
